scratch-org-def: config/project-scratch-def.json
assign-permset: true
permset-name: Mass_Action_Admin
run-apex-tests: false
delete-scratch-org: false
show-scratch-org-url: true
open-path: /one/one.app#/sObject/Mass_Action_Configuration__c/list
